In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from typing import List

In [18]:
df = pd.read_csv("data/raw/heart_cleveland_upload.csv")

In [5]:
X, y = train_test_split(df, test_size=0.2)

In [6]:
df.shape, X.shape, y.shape

((297, 14), (237, 14), (60, 14))

In [8]:
def build_numerical_pipeline() -> Pipeline:
    num_pipeline = Pipeline([
        ("scaler", StandardScaler())
    ])
    return num_pipeline

def build_transformer(numerical_features: List[str]) -> ColumnTransformer:
    transformer = ColumnTransformer(
        [
            (
                "numerical_pipeline",
                build_numerical_pipeline(),
                numerical_features,
            ),
        ]
    )
    return transformer

In [14]:
transformer = build_transformer(df.columns)
preprocess_train_df = transformer.fit_transform(df)
print(preprocess_train_df.shape, df.shape)

(297, 14) (297, 14)

In [20]:
df[df.columns] = preprocess_train_df
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,1.600302,0.691095,-2.240629,1.596266,-0.257179,2.430427,1.010199,-0.812095,-0.696419,-0.820813,0.643781,0.344824,-0.874292,-0.925338
1,1.600302,-1.446980,-2.240629,0.468418,-0.160859,-0.411450,-1.003419,0.061157,-0.696419,0.639470,-0.976583,1.411625,-0.874292,-0.925338
2,1.268242,-1.446980,-2.240629,1.032342,-0.411292,-0.411450,-1.003419,-1.554358,-0.696419,1.326662,2.264145,-0.721976,-0.874292,-0.925338
3,1.157555,0.691095,-2.240629,0.355633,0.667499,2.430427,1.010199,1.065396,-0.696419,0.295874,0.643781,0.344824,-0.874292,1.080686
4,1.046868,0.691095,-2.240629,-1.223355,-0.700254,-0.411450,1.010199,-0.244481,1.435916,0.639470,0.643781,-0.721976,-0.874292,-0.925338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,-1.609620,0.691095,0.873880,1.145127,-0.469085,-0.411450,-1.003419,1.371034,-0.696419,-0.906712,-0.976583,-0.721976,1.219778,1.080686
293,-1.720306,0.691095,0.873880,-0.772215,-0.546141,-0.411450,-1.003419,-0.419131,-0.696419,0.124076,0.643781,-0.721976,1.219778,1.080686
294,-2.163054,0.691095,0.873880,-0.659431,-0.950688,-0.411450,-1.003419,-0.855757,1.435916,0.467672,0.643781,-0.721976,1.219778,1.080686
295,-2.163054,-1.446980,0.873880,0.355633,-1.239649,-0.411450,-1.003419,1.414697,-0.696419,0.295874,-0.976583,-0.721976,-0.874292,-0.925338
296,-2.163054,0.691095,0.873880,-0.321076,0.667499,-0.411450,1.010199,0.279470,1.435916,-0.906712,-0.976583,-0.721976,1.219778,1.080686

In [15]:
preprocess_train_df

array([[ 1.60030243,  0.69109474, -2.24062879, ...,  0.34482438,
        -0.87429153, -0.92533778],
       [ 1.60030243, -1.44697961, -2.24062879, ...,  1.41162482,
        -0.87429153, -0.92533778],
       [ 1.26824154, -1.44697961, -2.24062879, ..., -0.72197605,
        -0.87429153, -0.92533778],
       ...,
       [-2.16305433,  0.69109474,  0.87388018, ..., -0.72197605,
         1.21977769,  1.08068645],
       [-2.16305433, -1.44697961,  0.87388018, ..., -0.72197605,
        -0.87429153, -0.92533778],
       [-2.16305433,  0.69109474,  0.87388018, ..., -0.72197605,
         1.21977769,  1.08068645]])

In [16]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,40,1,3,152,223,0,0,181,0,0.0,0,0,2,1
293,39,1,3,118,219,0,0,140,0,1.2,1,0,2,1
294,35,1,3,120,198,0,0,130,1,1.6,1,0,2,1
295,35,0,3,138,183,0,0,182,0,1.4,0,0,0,0
296,35,1,3,126,282,0,2,156,1,0.0,0,0,2,1